# Auto-generated by GruntKill

import subprocess
import logging
import os
from typing import Any, Dict, Optional

# Configure logging for AWS Lambda
logger = logging.getLogger()
logger.setLevel(logging.INFO)

# Remove default handlers and add a custom one for consistent formatting
if logger.handlers:
    for handler in logger.handlers:
        logger.removeHandler(handler)

handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter(
    '%(asctime)s - %(levelname)s - %(funcName)s - %(message)s'
))
logger.addHandler(handler)


class CommandExecutionError(Exception):
    """Custom exception for command execution failures."""
    pass


def run_command(command: str, cwd: Optional[str] = None) -> Dict[str, Any]:
    """
    Execute a shell command and return the result.
    
    Args:
        command: The shell command to execute
        cwd: Working directory for the command
        
    Returns:
        Dictionary containing stdout, stderr, and return code
        
    Raises:
        CommandExecutionError: If the command fails
    """
    logger.info(f"Executing command: {command}")
    
    try:
        result = subprocess.run(
            command,
            shell=True,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=300  # 5 minute timeout
        )
        
        output = {
            'stdout': result.stdout,
            'stderr': result.stderr,
            'returncode': result.returncode
        }
        
        if result.returncode != 0:
            logger.error(f"Command failed with return code {result.returncode}")
            logger.error(f"stderr: {result.stderr}")
            raise CommandExecutionError(
                f"Command '{command}' failed with return code {result.returncode}: {result.stderr}"
            )
        
        logger.info(f"Command completed successfully")
        if result.stdout:
            logger.debug(f"stdout: {result.stdout}")
            
        return output
        
    except subprocess.TimeoutExpired:
        logger.error(f"Command timed out: {command}")
        raise CommandExecutionError(f"Command '{command}' timed out after 300 seconds")


def setup_git_config(repo_path: str) -> None:
    """
    Configure git settings required for commits.
    
    Args:
        repo_path: Path to the git repository
    """
    logger.info("Setting up git configuration")
    
    # Set git user email if not already set
    git_email = os.environ.get('GIT_USER_EMAIL', 'automation@gruntkill.com')
    git_name = os.environ.get('GIT_USER_NAME', 'GruntKill Automation')
    
    run_command(f'git config user.email "{git_email}"', cwd=repo_path)
    run_command(f'git config user.name "{git_name}"', cwd=repo_path)
    
    logger.info("Git configuration complete")


def build_commit_push(
    repo_path: str,
    commit_message: str,
    branch: str = "main"
) -> Dict[str, Any]:
    """
    Execute the build, commit, and push workflow.
    
    This function performs the following steps:
    1. Run npm build
    2. Stage all changes
    3. Commit with the provided message
    4. Push to the specified branch
    
    Args:
        repo_path: Path to the repository
        commit_message: Git commit message
        branch: Target branch for push (default: main)
        
    Returns:
        Dictionary containing results of each step
    """
    results = {
        'build': None,
        'add': None,
        'commit': None,
        'push': None,
        'success': False
    }
    
    # Step 1: Run the build process
    logger.info("Step 1: Running npm build")
    results['build'] = run_command('npm run build', cwd=repo_path)
    
    # Step 2: Stage all changes for commit
    logger.info("Step 2: Staging all changes")
    results['add'] = run_command('git add .', cwd=repo_path)
    
    # Step 3: Check if there are changes to commit
    logger.info("Step 3: Checking for changes to commit")
    status_result = subprocess.run(
        'git status --porcelain',
        shell=True,
        cwd=repo_path,
        capture_output=True,
        text=True
    )
    
    if not status_result.stdout.strip():
        logger.info("No changes to commit, skipping commit and push")
        results['commit'] = {'message': 'No changes to commit'}
        results['push'] = {'message': 'Skipped - no changes'}
        results['success'] = True
        return results
    
    # Step 4: Commit changes with the provided message
    logger.info("Step 4: Committing changes")
    # Escape double quotes in commit message to prevent shell injection
    safe_message = commit_message.replace('"', '\\"')
    results['commit'] = run_command(
        f'git commit -m "{safe_message}"',
        cwd=repo_path
    )
    
    # Step 5: Push to the remote branch
    logger.info(f"Step 5: Pushing to origin/{branch}")
    results['push'] = run_command(
        f'git push origin {branch}',
        cwd=repo_path
    )
    
    results['success'] = True
    logger.info("Build, commit, and push workflow completed successfully")
    
    return results


def handler(event: Dict[str, Any], context: Any) -> Dict[str, Any]:
    """
    AWS Lambda handler function for the build_commit_push automation.
    
    This handler is triggered on a schedule and executes the build,
    commit, and push workflow for the configured repository.
    
    Args:
        event: Lambda event object containing:
            - repo_path (optional): Path to the repository
            - commit_message (optional): Custom commit message
            - branch (optional): Target branch (default: main)
        context: Lambda context object
        
    Returns:
        Dictionary containing execution status and results
    """
    logger.info("Lambda handler invoked")
    logger.info(f"Event: {event}")
    
    # Extract configuration from event or environment variables
    repo_path = event.get('repo_path', os.environ.get('REPO_PATH', '/tmp/repo'))
    commit_message = event.get(
        'commit_message',
        os.environ.get('COMMIT_MESSAGE', 'Automated build and commit by GruntKill')
    )
    branch = event.get('branch', os.environ.get('GIT_BRANCH', 'main'))
    
    # Validate required parameters
    if not repo_path:
        logger.error("Repository path not provided")
        return {
            'statusCode': 400,
            'body': {
                'success': False,
                'error': 'Repository path is required'
            }
        }
    
    try:
        # Ensure repository directory exists
        if not os.path.exists(repo_path):
            logger.error(f"Repository path does not exist: {repo_path}")
            return {
                'statusCode': 400,
                'body': {
                    'success': False,
                    'error': f'Repository path does not exist: {repo_path}'
                }
            }
        
        # Setup git configuration for commits
        setup_git_config(repo_path)
        
        # Execute the main workflow
        results = build_commit_push(
            repo_path=repo_path,
            commit_message=commit_message,
            branch=branch
        )
        
        logger.info("Automation completed successfully")
        
        return {
            'statusCode': 200,
            'body': {
                'success': True,
                'message': 'Build, commit, and push completed successfully',