import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import json
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()

client = Anthropic()

def generate_script(pattern: dict) -> str:
    """Ask Claude to write a Python automation script for a pattern"""
    
    pattern_name   = pattern.get('pattern_name', 'unknown')
    description    = pattern.get('description', '')
    commands       = pattern.get('commands', '')
    
    print(f"\n⚙️  Generating script for: {pattern_name}")
    
    prompt = f"""You are an expert Python automation engineer.

A developer repeatedly does this task:
- Pattern name: {pattern_name}
- Description: {description}
- Commands they run: {commands}

Write a complete Python script that automates this task.
The script will run on AWS Lambda on a schedule.

Requirements:
- Include a handler(event, context) function for Lambda
- Add proper error handling with try/except
- Add logging using Python's logging module
- Add comments explaining each step
- Make it production ready
- At the top add a comment: # Auto-generated by GruntKill

Return only the Python code. No explanation, no markdown fences.
"""

    response = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=2000,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    
    script = response.content[0].text.strip()
    script = script.replace("```python", "").replace("```", "").strip()
    
    print(f"✓ Script generated for {pattern_name} ({len(script.splitlines())} lines)")
    return script

def generate_all_scripts(patterns_file="detected_patterns.json"):
    """Generate scripts for all high feasibility patterns"""
    
    if not os.path.exists(patterns_file):
        print("⚠️  No patterns file found. Run pattern_detector.py first.")
        return {}
    
    with open(patterns_file) as f:
        patterns = json.load(f)
    
    scripts = {}
    
    for pattern in patterns:
        feasibility = pattern.get('automation_feasibility', '').lower()
        
        if feasibility == 'high':
            script = generate_script(pattern)
            scripts[pattern['pattern_name']] = {
                "pattern": pattern,
                "script":  script
            }
            
            # Save each script to a file
            filename = f"generated_{pattern['pattern_name']}.py"
            with open(filename, "w") as f:
                f.write(script)
            print(f"✓ Saved to {filename}")
        else:
            print(f"⏭️  Skipping {pattern.get('pattern_name')} — feasibility: {feasibility}")
    
    return scripts

if __name__ == "__main__":
    print("🤖 GruntKill Script Generator")
    print("=" * 40)
    scripts = generate_all_scripts()
    
    if scripts:
        print(f"\n✓ Generated {len(scripts)} script(s)")
        for name, data in scripts.items():
            print(f"\n{'='*60}")
            print(f"Script: {name}")
            print(f"{'='*60}")
            print(data['script'][:500] + "..." if len(data['script']) > 500 else data['script'])
    else:
        print("\n⚠️  No high feasibility patterns to generate scripts for.")
        print("    Run pattern_detector.py first and make sure you have logged commands.")